### ISSUE TITLE
Bug: clear/stop method

### ISSUE THREAD

**Issue by weebik** [YarynaRachkevych1/python-logo#19]
## Describe the bug

The clear method doesn't stop the running program

### Steps to reproduce

Run very long program then hit clear

### Expected behavior

The turtle should stop, go back to the center of the canvas, and the canvas should be cleared

### Environment

- OS: WSL2 Windows Subsystem For Linux

**Comment by mkalitka** [comment]
Fixed with this [commit](https://github.com/YarynaRachkevych1/python-logo/commit/196a1798374196e00dea0f82a9ff6d40a5cbd6f2)
